### ISSUE TITLE
Support cross account Route53 hosted zones with IAM role

### ISSUE THREAD

**Issue by johnlinvc** [sorah/acmesmith#36]
Hi.
The use case here is that we want a central storage in one AWS account and Route53 hosted zone in multiple AWS accounts.
We've made a working prototype for this feature. We want to discuss how the config should look like before create a pr.

The proposed config format is 
```YAML
challenge_responders:
  - route53:
      # aws_access_key: # aws credentials (optional); If omit, default configuration of aws-sdk use will be used.
      #   access_key_id:
      #   secret_access_key:
      #   session_token:
      # hosted_zone_map: # hosted zone map (optional); This is to specify exactly one hosted zone to use. This will be required when there are multiple hosted zone with same domain name. Usually
      #   "example.org.": "/hostedzone/DEADBEEF"
      #   alternative format, required when the hosted zone is in an account different from the storage account. or having zones in multiple accounts.
      #   "example.com.": 
      #       id: "/hostedzone/8BADFOOD"
      #       role_arn: "arn:aws:iam::123451234512:role/switched_role"    
```

**Comment by sorah** [comment]
Sounds fancy.

I'm just curious about consistency across AWS related components, in this case, this means S3 and ACM.

Perhaps it's the time to extract these similar logics into a module to implement that feature:

- https://github.com/sorah/acmesmith/blob/05493723e7a597536ccef4d76c3361e5e6d21246/lib/acmesmith/challenge_responders/route53.rb#L22
- https://github.com/sorah/acmesmith/blob/05493723e7a597536ccef4d76c3361e5e6d21246/lib/acmesmith/storages/s3.rb#L27

**Comment by sorah** [comment]
PRs are always welcome and I'm positive for this feature. Looking forward to it!

**Comment by sorah** [comment]
Sorry for being late to reply. Per-domain configuration on hosted zone sounds ad-hoc to me, so I figured out it's better to add filtering feature on ChallengeResponder itself. As I'm being late to give a reply, I implemented filter & assume_role feature and have just released it.

Please take a look at [v2.3.0](https://github.com/sorah/acmesmith/releases/tag/v2.3.0):

```yaml
challenge_responders:
  # only under example.org
  - route53:
      assume_role:
        iam_role: aws:iam:arn:::...
    filter:
      domain_name_suffix:
        - example.org
  # Anything other than not under example.org
  - route53: {}
```
